#!/usr/bin/env bash
# Spike A follow-up, MAC SIDE: does the mac's OWN transmission keep its radio
# awake and its inbound path fast?
#
# Run this ON the macbook while the Linux host measures continuously toward
# the mac (from the linux box: ping -D -i 1.13 macbook.local | tee probe.log).
# This script cycles keepalive arms generated BY the mac and prints exact arm
# boundaries so the probe log can be split by timestamp afterward.
#
#   sudo ./mac-keepalive.sh <linux-host> [seconds-per-arm]
#
# sudo because macOS ping requires root for intervals under 0.1 s (the 20, 50
# and 100 Hz arms). The 0 Hz arm is pure idle: the mac originates nothing.
#
# Optional extra arms worth running manually afterward:
#   sudo ifconfig awdl0 down   # re-enables itself; rerun before each arm
#   pmset -g                   # record power settings alongside RESULT.md

set -euo pipefail
export LC_ALL=C

TARGET=${1:?usage: sudo ./mac-keepalive.sh <linux-host> [seconds-per-arm]}
ARM_SECS=${2:-60}
RATES=(0 10 20 50 100)

PID=""
cleanup() { [[ -n "$PID" ]] && kill "$PID" 2>/dev/null || true; }
trap cleanup EXIT

echo "awdl0 status: $(ifconfig awdl0 2>/dev/null | grep -o 'status: .*' || echo unknown)"

for RATE in "${RATES[@]}"; do
  echo "ARM ${RATE}Hz START $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  if [[ "$RATE" != "0" ]]; then
    INT=$(awk "BEGIN{printf \"%.3f\", 1/$RATE}")
    ping -q -i "$INT" "$TARGET" >/dev/null 2>&1 &
    PID=$!
    sleep 2
    if ! kill -0 "$PID" 2>/dev/null; then
      echo "ARM ${RATE}Hz FAILED: keepalive ping exited (need sudo for sub-0.1s intervals)"
      PID=""
      continue
    fi
  fi
  sleep "$ARM_SECS"
  if [[ -n "$PID" ]]; then
    kill "$PID" 2>/dev/null || true
    wait "$PID" 2>/dev/null || true
    PID=""
  fi
  echo "ARM ${RATE}Hz END $(date -u +%Y-%m-%dT%H:%M:%SZ)"
done
echo "all arms done"
